server:
  port: 9013 #服务端口号
spring:
  application:
    name: cloud-demo-security-Oauht2
    #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/spring_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    # Redis数据库索引（默认为0）
    database: 7
    #连接超时时间（毫秒）
    timeout: 43200000
    # Redis服务器地址
    host: 192.168.14.92
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 512
        # 连接池中的最小空闲连接
        min-idle: 100


