server:
  port: 9001 #服务端口号
spring:
  application:
    name: cloud-demo-mybatis-plus
    #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/spring_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
#  mapper-locations: classpath:mappers/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.xkcoding.orm.mybatis.plus.entity
#  global-config:
#    # 数据库相关配置
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: auto
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: NOT_EMPTY
#      #驼峰下划线转换
#      table-underline: true
#      #是否开启大写命名，默认不开启
#      #capital-mode: true
#      #逻辑删除配置
#      #logic-delete-value: 1
#      #logic-not-delete-value: 0
#      db-type: mysql
#    #刷新mapper 调试神器
#    refresh: true
#  # 原生配置
  configuration:
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#    cache-enabled: true
