server:
  port: 8001 #服务端口号
spring:
  application:
    name: register-center #应用名称
eureka:
  dashboard:
    path: /register-center
  instance:
      #实例主机名（建议使用IP）集群时名称为default中配置，单体时hostname无法解析域名会报错
      hostname: eureka-server-1
      prefer-ip-address: true #注册服务时是否使用IP注册
      instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册到server的实例
      #续约更新时间间隔（默认30秒，eureka client发送心跳给server端的频率。如果在设定时间后，server端没有收到client的心跳，则将摘除该instance）
#      lease-renewal-interval-in-seconds: 3
      #续约到期时间（默认为90秒，表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance）
#      lease-expiration-duration-in-seconds: 9
  server:
    #关闭自我保护【默认为true，用于本地测试时配置-快速剔除失效服务】
    enable-self-preservation: true
    #检查失效服务间隔【默认60秒，用于本地测试时配置-快速剔除失效服务】
    eviction-interval-timer-in-ms: 30000
  client:
    #是否向服务注册中心注册自己【非集群服务配置，不将自己当客户端注册到自己】
    register-with-eureka: false
    #是否检索服务（去注册中心获取其他服务的地址）【非集群服务配置，不从服务端拉取服务列表】
    fetch-registry: false
    serviceUrl:
      # 用于单机
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（集群）。
#      defaultZone: http://local-server-1:8001/eureka/,http://local-server-2:8002/eureka/


