#server:
#  port: 9118 #服务端口号
#spring:
#  application:
#    name: service-platform-analysis-h
#  servlet:
#      multipart:
#        enabled: true
#        max-file-size: 20MB
#        max-request-size: 20MB
#    #数据库配置
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.14.85:3306/ccx_credit_risk_v4?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: root
#
#  rabbitmq:
#    ####连接地址
#    host: 192.168.14.90
#    ####端口号
#    port: 5672
#    ####账号
#    username: ccx
#    ####密码
#    password: ccx
#    ### 地址  主机独立的virtualhost
#    virtual-host: ccx-90
#
#eureka:
#  client:
#    security:
#      user: register
#      password: ccxnode2020
#    serviceUrl:
#      defaultZone: http://${eureka.client.security.user}:${eureka.client.security.password}@192.168.14.90:8001/eureka/ #注册中心的注册地址
#    healthcheck:
#      enabled: true #开启健康检查
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #将Instance ID设置为IP:端口的形式
#    lease-renewal-interval-in-seconds: 1 #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
#    lease-expiration-duration-in-seconds: 2  # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
#
## 分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  page-size-zero: true
#  support-methods-arguments: true
#  params: count=countSql
#
## mybatis 配置
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: ccx.cloud.platform.analysis.api.model
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 通用 Mapper 配置
#mapper:
#  identity: MYSQL
#  not-empty: false
#  mappers: ccx.cloud.platform.analysis.api.base.core.Mapper
#
##日志
#logging:
#  level:
#    ccx.cloud.platform.analysis.api: INFO
#
##配置
#config-path: src/main/resources/config
#pdf-path: d:/ccrm/pdf   #/ccrm/pdf
#
#platform-analysis:
#  region:
##    modal: http://192.168.14.90:8118/modal/rating #城投区域模型
#    modal: http://model-platform-v4-2-0/modal/rating #城投区域模型
#    indicators: ${config-path}/regionIndex.xml #区域定量指标
#    area-index: ${config-path}/AreaIndex.xml #区域定量指标
#    region-sort-path: ${config-path}/regionSort.xml
#  enterprise:
#    getPublicRating: http://101.227.67.32:32000/api/company/ratingList #根据企业列表过去各自最高公开评级
#    indicators: ${config-path}/entIndex.xml #指标集合
##    modal: http://192.168.14.90:8119/modal/rating #城投企业模型
#    modal: http://model-platform-enterprise-v4-2-0/modal/rating #城投企业模型
#    company-public-rating-url: http://101.227.67.32:32000/api/company/rating #外部评级
#    public-report-api: http://creditrisk.ccx.com.cn:10012/report/getPublicReport?credit_code={creditCode}&type=4&year={year}  #获取年报
#    report-template-path: ${config-path}/pdf/report_template_1Y_v4_zong_he.xlsx #年报模板
#  report:
#    rating-threads: 20 #
#    report-threads: 4 #
#    wind-token: 1234567890ABCDE
#    logo-path: logo.png
#    background-path: background.png
##    wkhtmltopdf-server: http://creditrisk.ccx.com.cn:12050/convertHtmlFile?pageOffset=%d
#    wkhtmltopdf-server: http://service-pdf-convert/convertHtmlFile?pageOffset=%d
#    repository-region-report-temp: ${config-path}/pdf/repositoryRegion
#    repository-region-report: ${pdf-path}/repositoryRegion/
#    repository-enterprise-report-temp: ${config-path}/pdf/repositoryEnterprise
#    repository-enterprise-report: ${pdf-path}/repositoryEnterprise/